[2023-04-15 22:51:28,749] {processor.py:162} INFO - Started process (PID=36) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:51:28,751] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:51:28,752] {logging_mixin.py:109} INFO - [2023-04-15 22:51:28,752] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:51:28,790] {logging_mixin.py:109} INFO - [2023-04-15 22:51:28,789] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:51:28,790] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:51:28,827] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.084 seconds
[2023-04-15 22:51:58,874] {processor.py:162} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:51:58,876] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:51:58,877] {logging_mixin.py:109} INFO - [2023-04-15 22:51:58,877] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:51:58,886] {logging_mixin.py:109} INFO - [2023-04-15 22:51:58,885] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:51:58,887] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:51:58,923] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2023-04-15 22:52:29,045] {processor.py:162} INFO - Started process (PID=38) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:52:29,048] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:52:29,049] {logging_mixin.py:109} INFO - [2023-04-15 22:52:29,049] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:52:29,062] {logging_mixin.py:109} INFO - [2023-04-15 22:52:29,061] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:52:29,063] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:52:29,108] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.070 seconds
[2023-04-15 22:52:59,165] {processor.py:162} INFO - Started process (PID=39) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:52:59,166] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:52:59,167] {logging_mixin.py:109} INFO - [2023-04-15 22:52:59,167] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:52:59,175] {logging_mixin.py:109} INFO - [2023-04-15 22:52:59,174] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:52:59,175] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:52:59,212] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2023-04-15 22:53:29,310] {processor.py:162} INFO - Started process (PID=40) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:53:29,325] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:53:29,325] {logging_mixin.py:109} INFO - [2023-04-15 22:53:29,325] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:53:29,332] {logging_mixin.py:109} INFO - [2023-04-15 22:53:29,332] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:53:29,333] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:53:29,374] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2023-04-15 22:53:59,434] {processor.py:162} INFO - Started process (PID=41) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:53:59,436] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:53:59,437] {logging_mixin.py:109} INFO - [2023-04-15 22:53:59,437] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:53:59,444] {logging_mixin.py:109} INFO - [2023-04-15 22:53:59,443] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:53:59,444] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:53:59,486] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2023-04-15 22:54:29,605] {processor.py:162} INFO - Started process (PID=42) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:54:29,624] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:54:29,626] {logging_mixin.py:109} INFO - [2023-04-15 22:54:29,626] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:54:29,652] {logging_mixin.py:109} INFO - [2023-04-15 22:54:29,650] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:54:29,654] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:54:29,706] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.108 seconds
[2023-04-15 22:54:59,775] {processor.py:162} INFO - Started process (PID=43) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:54:59,777] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:54:59,778] {logging_mixin.py:109} INFO - [2023-04-15 22:54:59,778] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:54:59,787] {logging_mixin.py:109} INFO - [2023-04-15 22:54:59,786] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:54:59,787] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:54:59,904] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.133 seconds
[2023-04-15 22:55:29,973] {processor.py:162} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:55:30,006] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:55:30,006] {logging_mixin.py:109} INFO - [2023-04-15 22:55:30,006] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:55:30,012] {logging_mixin.py:109} INFO - [2023-04-15 22:55:30,011] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:55:30,012] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:55:30,063] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.093 seconds
[2023-04-15 22:56:00,078] {processor.py:162} INFO - Started process (PID=45) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:56:00,080] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:56:00,081] {logging_mixin.py:109} INFO - [2023-04-15 22:56:00,080] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:56:00,089] {logging_mixin.py:109} INFO - [2023-04-15 22:56:00,088] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:56:00,089] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:56:00,133] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.059 seconds
[2023-04-15 22:56:30,303] {processor.py:162} INFO - Started process (PID=46) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:56:30,317] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:56:30,318] {logging_mixin.py:109} INFO - [2023-04-15 22:56:30,318] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:56:30,328] {logging_mixin.py:109} INFO - [2023-04-15 22:56:30,327] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:56:30,329] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:56:30,378] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.084 seconds
[2023-04-15 22:57:00,444] {processor.py:162} INFO - Started process (PID=47) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:57:00,447] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:57:00,448] {logging_mixin.py:109} INFO - [2023-04-15 22:57:00,447] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:57:00,458] {logging_mixin.py:109} INFO - [2023-04-15 22:57:00,457] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:57:00,459] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:57:00,515] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2023-04-15 22:57:30,551] {processor.py:162} INFO - Started process (PID=48) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:57:30,565] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:57:30,566] {logging_mixin.py:109} INFO - [2023-04-15 22:57:30,566] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:57:30,578] {logging_mixin.py:109} INFO - [2023-04-15 22:57:30,577] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:57:30,579] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:57:30,617] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.072 seconds
[2023-04-15 22:58:00,707] {processor.py:162} INFO - Started process (PID=49) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:58:00,709] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:58:00,710] {logging_mixin.py:109} INFO - [2023-04-15 22:58:00,710] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:58:00,721] {logging_mixin.py:109} INFO - [2023-04-15 22:58:00,720] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:58:00,722] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:58:00,799] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.102 seconds
[2023-04-15 22:58:30,885] {processor.py:162} INFO - Started process (PID=50) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:58:30,900] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:58:30,901] {logging_mixin.py:109} INFO - [2023-04-15 22:58:30,901] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:58:30,910] {logging_mixin.py:109} INFO - [2023-04-15 22:58:30,909] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:58:30,910] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:58:31,264] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.384 seconds
[2023-04-15 22:59:01,339] {processor.py:162} INFO - Started process (PID=51) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:59:01,340] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:59:01,340] {logging_mixin.py:109} INFO - [2023-04-15 22:59:01,340] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:59:01,347] {logging_mixin.py:109} INFO - [2023-04-15 22:59:01,346] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:59:01,348] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:59:01,387] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2023-04-15 22:59:31,455] {processor.py:162} INFO - Started process (PID=52) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 22:59:31,466] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 22:59:31,467] {logging_mixin.py:109} INFO - [2023-04-15 22:59:31,467] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 22:59:31,473] {logging_mixin.py:109} INFO - [2023-04-15 22:59:31,473] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 22:59:31,474] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 22:59:31,515] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2023-04-15 23:00:01,564] {processor.py:162} INFO - Started process (PID=53) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:01,566] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:00:01,567] {logging_mixin.py:109} INFO - [2023-04-15 23:00:01,567] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:01,578] {logging_mixin.py:109} INFO - [2023-04-15 23:00:01,577] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:00:01,578] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:01,627] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2023-04-15 23:00:31,672] {processor.py:162} INFO - Started process (PID=54) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:31,690] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:00:31,691] {logging_mixin.py:109} INFO - [2023-04-15 23:00:31,691] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:31,698] {logging_mixin.py:109} INFO - [2023-04-15 23:00:31,697] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:00:31,698] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:31,756] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.088 seconds
[2023-04-15 23:00:49,798] {processor.py:162} INFO - Started process (PID=55) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:49,800] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:00:49,801] {logging_mixin.py:109} INFO - [2023-04-15 23:00:49,801] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:49,808] {logging_mixin.py:109} INFO - [2023-04-15 23:00:49,807] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:00:49,808] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:00:49,863] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2023-04-15 23:01:19,935] {processor.py:162} INFO - Started process (PID=56) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:01:19,937] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:01:19,939] {logging_mixin.py:109} INFO - [2023-04-15 23:01:19,938] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:01:19,949] {logging_mixin.py:109} INFO - [2023-04-15 23:01:19,948] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:01:19,950] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:01:20,049] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.129 seconds
[2023-04-15 23:01:50,121] {processor.py:162} INFO - Started process (PID=57) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:01:50,166] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:01:50,167] {logging_mixin.py:109} INFO - [2023-04-15 23:01:50,167] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:01:50,175] {logging_mixin.py:109} INFO - [2023-04-15 23:01:50,174] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:01:50,175] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:01:50,245] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.127 seconds
[2023-04-15 23:02:20,314] {processor.py:162} INFO - Started process (PID=58) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:02:20,329] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:02:20,330] {logging_mixin.py:109} INFO - [2023-04-15 23:02:20,329] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:02:20,341] {logging_mixin.py:109} INFO - [2023-04-15 23:02:20,339] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:02:20,341] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:02:20,390] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
[2023-04-15 23:02:50,446] {processor.py:162} INFO - Started process (PID=59) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:02:50,447] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:02:50,448] {logging_mixin.py:109} INFO - [2023-04-15 23:02:50,448] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:02:50,455] {logging_mixin.py:109} INFO - [2023-04-15 23:02:50,455] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:02:50,456] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:02:50,493] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2023-04-15 23:03:20,552] {processor.py:162} INFO - Started process (PID=60) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:03:20,554] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:03:20,556] {logging_mixin.py:109} INFO - [2023-04-15 23:03:20,555] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:03:20,568] {logging_mixin.py:109} INFO - [2023-04-15 23:03:20,567] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:03:20,569] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:03:20,613] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.072 seconds
[2023-04-15 23:03:50,659] {processor.py:162} INFO - Started process (PID=61) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:03:50,675] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:03:50,677] {logging_mixin.py:109} INFO - [2023-04-15 23:03:50,676] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:03:50,685] {logging_mixin.py:109} INFO - [2023-04-15 23:03:50,684] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:03:50,686] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:03:50,749] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.097 seconds
[2023-04-15 23:04:20,814] {processor.py:162} INFO - Started process (PID=62) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:04:20,816] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:04:20,818] {logging_mixin.py:109} INFO - [2023-04-15 23:04:20,818] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:04:20,833] {logging_mixin.py:109} INFO - [2023-04-15 23:04:20,831] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:04:20,834] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:04:20,877] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.071 seconds
[2023-04-15 23:04:50,897] {processor.py:162} INFO - Started process (PID=63) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:04:50,911] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:04:50,912] {logging_mixin.py:109} INFO - [2023-04-15 23:04:50,912] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:04:50,919] {logging_mixin.py:109} INFO - [2023-04-15 23:04:50,918] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:04:50,919] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:04:50,964] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.071 seconds
[2023-04-15 23:05:21,025] {processor.py:162} INFO - Started process (PID=64) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:05:21,026] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:05:21,027] {logging_mixin.py:109} INFO - [2023-04-15 23:05:21,027] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:05:21,034] {logging_mixin.py:109} INFO - [2023-04-15 23:05:21,033] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:05:21,034] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:05:21,085] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2023-04-15 23:05:51,125] {processor.py:162} INFO - Started process (PID=65) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:05:51,144] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:05:51,145] {logging_mixin.py:109} INFO - [2023-04-15 23:05:51,145] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:05:51,153] {logging_mixin.py:109} INFO - [2023-04-15 23:05:51,152] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:05:51,153] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:05:51,195] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2023-04-15 23:06:21,233] {processor.py:162} INFO - Started process (PID=66) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:06:21,234] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:06:21,235] {logging_mixin.py:109} INFO - [2023-04-15 23:06:21,235] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:06:21,242] {logging_mixin.py:109} INFO - [2023-04-15 23:06:21,241] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:06:21,243] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:06:21,308] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.079 seconds
[2023-04-15 23:06:51,363] {processor.py:162} INFO - Started process (PID=67) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:06:51,365] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:06:51,366] {logging_mixin.py:109} INFO - [2023-04-15 23:06:51,365] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:06:51,373] {logging_mixin.py:109} INFO - [2023-04-15 23:06:51,372] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:06:51,373] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:06:51,414] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2023-04-15 23:07:21,481] {processor.py:162} INFO - Started process (PID=68) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:07:21,484] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:07:21,486] {logging_mixin.py:109} INFO - [2023-04-15 23:07:21,485] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:07:21,498] {logging_mixin.py:109} INFO - [2023-04-15 23:07:21,497] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:07:21,499] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:07:21,548] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.074 seconds
[2023-04-15 23:07:51,575] {processor.py:162} INFO - Started process (PID=69) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:07:51,593] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:07:51,594] {logging_mixin.py:109} INFO - [2023-04-15 23:07:51,593] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:07:51,601] {logging_mixin.py:109} INFO - [2023-04-15 23:07:51,600] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:07:51,601] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:07:51,646] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2023-04-15 23:08:21,706] {processor.py:162} INFO - Started process (PID=70) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:08:21,707] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:08:21,707] {logging_mixin.py:109} INFO - [2023-04-15 23:08:21,707] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:08:21,714] {logging_mixin.py:109} INFO - [2023-04-15 23:08:21,713] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:08:21,714] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:08:21,758] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2023-04-15 23:08:51,811] {processor.py:162} INFO - Started process (PID=71) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:08:51,826] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:08:51,827] {logging_mixin.py:109} INFO - [2023-04-15 23:08:51,827] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:08:51,837] {logging_mixin.py:109} INFO - [2023-04-15 23:08:51,836] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:08:51,841] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:08:51,891] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.092 seconds
[2023-04-15 23:09:21,913] {processor.py:162} INFO - Started process (PID=72) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:09:21,915] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:09:21,916] {logging_mixin.py:109} INFO - [2023-04-15 23:09:21,916] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:09:21,925] {logging_mixin.py:109} INFO - [2023-04-15 23:09:21,924] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:09:21,925] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:09:21,973] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2023-04-15 23:09:52,064] {processor.py:162} INFO - Started process (PID=73) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:09:52,067] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:09:52,068] {logging_mixin.py:109} INFO - [2023-04-15 23:09:52,067] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:09:52,075] {logging_mixin.py:109} INFO - [2023-04-15 23:09:52,074] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:09:52,075] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:09:52,122] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2023-04-15 23:10:22,179] {processor.py:162} INFO - Started process (PID=74) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:10:22,181] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:10:22,182] {logging_mixin.py:109} INFO - [2023-04-15 23:10:22,182] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:10:22,191] {logging_mixin.py:109} INFO - [2023-04-15 23:10:22,190] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:10:22,191] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:10:22,252] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.078 seconds
[2023-04-15 23:10:52,288] {processor.py:162} INFO - Started process (PID=75) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:10:52,305] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:10:52,305] {logging_mixin.py:109} INFO - [2023-04-15 23:10:52,305] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:10:52,312] {logging_mixin.py:109} INFO - [2023-04-15 23:10:52,312] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:10:52,313] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:10:52,371] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.087 seconds
[2023-04-15 23:11:22,404] {processor.py:162} INFO - Started process (PID=76) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:11:22,405] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:11:22,406] {logging_mixin.py:109} INFO - [2023-04-15 23:11:22,406] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:11:22,414] {logging_mixin.py:109} INFO - [2023-04-15 23:11:22,413] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:11:22,414] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:11:22,458] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2023-04-15 23:11:52,566] {processor.py:162} INFO - Started process (PID=77) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:11:52,569] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:11:52,570] {logging_mixin.py:109} INFO - [2023-04-15 23:11:52,570] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:11:52,581] {logging_mixin.py:109} INFO - [2023-04-15 23:11:52,580] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:11:52,581] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:11:52,623] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.070 seconds
[2023-04-15 23:12:22,697] {processor.py:162} INFO - Started process (PID=78) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:12:22,700] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:12:22,701] {logging_mixin.py:109} INFO - [2023-04-15 23:12:22,701] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:12:22,712] {logging_mixin.py:109} INFO - [2023-04-15 23:12:22,711] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:12:22,713] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:12:22,760] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2023-04-15 23:12:52,794] {processor.py:162} INFO - Started process (PID=79) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:12:52,815] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:12:52,816] {logging_mixin.py:109} INFO - [2023-04-15 23:12:52,816] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:12:52,823] {logging_mixin.py:109} INFO - [2023-04-15 23:12:52,822] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:12:52,823] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:12:52,880] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.089 seconds
[2023-04-15 23:13:22,921] {processor.py:162} INFO - Started process (PID=80) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:13:22,922] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:13:22,923] {logging_mixin.py:109} INFO - [2023-04-15 23:13:22,923] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:13:22,930] {logging_mixin.py:109} INFO - [2023-04-15 23:13:22,929] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:13:22,930] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:13:23,265] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.347 seconds
[2023-04-15 23:13:53,325] {processor.py:162} INFO - Started process (PID=81) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:13:53,341] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:13:53,341] {logging_mixin.py:109} INFO - [2023-04-15 23:13:53,341] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:13:53,348] {logging_mixin.py:109} INFO - [2023-04-15 23:13:53,347] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:13:53,348] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:13:53,391] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2023-04-15 23:14:23,438] {processor.py:162} INFO - Started process (PID=82) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:14:23,441] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:14:23,442] {logging_mixin.py:109} INFO - [2023-04-15 23:14:23,442] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:14:23,452] {logging_mixin.py:109} INFO - [2023-04-15 23:14:23,451] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:14:23,452] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:14:23,569] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.139 seconds
[2023-04-15 23:14:53,645] {processor.py:162} INFO - Started process (PID=83) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:14:53,664] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:14:53,665] {logging_mixin.py:109} INFO - [2023-04-15 23:14:53,665] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:14:53,673] {logging_mixin.py:109} INFO - [2023-04-15 23:14:53,673] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:14:53,674] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:14:53,723] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.085 seconds
[2023-04-15 23:15:23,762] {processor.py:162} INFO - Started process (PID=84) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:15:23,767] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:15:23,769] {logging_mixin.py:109} INFO - [2023-04-15 23:15:23,768] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:15:23,778] {logging_mixin.py:109} INFO - [2023-04-15 23:15:23,777] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:15:23,778] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:15:23,818] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2023-04-15 23:15:53,914] {processor.py:162} INFO - Started process (PID=85) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:15:53,923] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:15:53,924] {logging_mixin.py:109} INFO - [2023-04-15 23:15:53,923] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:15:53,930] {logging_mixin.py:109} INFO - [2023-04-15 23:15:53,929] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:15:53,930] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:15:53,972] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2023-04-15 23:16:24,038] {processor.py:162} INFO - Started process (PID=86) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:24,052] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:16:24,053] {logging_mixin.py:109} INFO - [2023-04-15 23:16:24,053] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:24,064] {logging_mixin.py:109} INFO - [2023-04-15 23:16:24,063] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 2, in <module>
    from airflow.operators.bash_operator import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-04-15 23:16:24,064] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:24,112] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.081 seconds
[2023-04-15 23:16:26,044] {processor.py:162} INFO - Started process (PID=87) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:26,045] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:16:26,045] {logging_mixin.py:109} INFO - [2023-04-15 23:16:26,045] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:26,060] {logging_mixin.py:109} INFO - [2023-04-15 23:16:26,059] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:16:26,061] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:26,126] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2023-04-15 23:16:56,320] {processor.py:162} INFO - Started process (PID=88) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:56,374] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:16:56,375] {logging_mixin.py:109} INFO - [2023-04-15 23:16:56,375] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:56,378] {logging_mixin.py:109} INFO - [2023-04-15 23:16:56,377] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:16:56,378] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:16:56,459] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.142 seconds
[2023-04-15 23:17:26,524] {processor.py:162} INFO - Started process (PID=89) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:17:26,536] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:17:26,537] {logging_mixin.py:109} INFO - [2023-04-15 23:17:26,537] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:17:26,540] {logging_mixin.py:109} INFO - [2023-04-15 23:17:26,539] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:17:26,540] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:17:26,583] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2023-04-15 23:17:56,624] {processor.py:162} INFO - Started process (PID=90) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:17:56,633] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:17:56,633] {logging_mixin.py:109} INFO - [2023-04-15 23:17:56,633] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:17:56,637] {logging_mixin.py:109} INFO - [2023-04-15 23:17:56,636] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:17:56,638] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:17:56,702] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.083 seconds
[2023-04-15 23:18:13,726] {processor.py:162} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:18:13,728] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:18:13,729] {logging_mixin.py:109} INFO - [2023-04-15 23:18:13,729] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:18:13,732] {logging_mixin.py:109} INFO - [2023-04-15 23:18:13,731] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:18:13,732] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:18:13,806] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.084 seconds
[2023-04-15 23:18:43,855] {processor.py:162} INFO - Started process (PID=92) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:18:43,877] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:18:43,877] {logging_mixin.py:109} INFO - [2023-04-15 23:18:43,877] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:18:43,881] {logging_mixin.py:109} INFO - [2023-04-15 23:18:43,880] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:18:43,881] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:18:43,934] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.083 seconds
[2023-04-15 23:19:00,959] {processor.py:162} INFO - Started process (PID=93) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:00,979] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:19:00,981] {logging_mixin.py:109} INFO - [2023-04-15 23:19:00,980] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:00,987] {logging_mixin.py:109} INFO - [2023-04-15 23:19:00,986] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:19:00,988] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:01,036] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.091 seconds
[2023-04-15 23:19:23,102] {processor.py:162} INFO - Started process (PID=94) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:23,148] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:19:23,149] {logging_mixin.py:109} INFO - [2023-04-15 23:19:23,149] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:23,154] {logging_mixin.py:109} INFO - [2023-04-15 23:19:23,153] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:19:23,155] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:23,220] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.126 seconds
[2023-04-15 23:19:31,132] {processor.py:162} INFO - Started process (PID=95) to work on /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:31,144] {processor.py:613} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2023-04-15 23:19:31,144] {logging_mixin.py:109} INFO - [2023-04-15 23:19:31,144] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:31,147] {logging_mixin.py:109} INFO - [2023-04-15 23:19:31,147] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from data_processing import *
ModuleNotFoundError: No module named 'data_processing'
[2023-04-15 23:19:31,148] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2023-04-15 23:19:31,194] {processor.py:170} INFO - Processing /opt/airflow/dags/test_dag.py took 0.065 seconds
